name: PDT Tailwind Traders PR Workflow
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - AnotherBranch
jobs:
    
  build:
    if: (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: windows-latest
    steps:
      
    # checkout code from repo
    - name: Checkout code
      uses: actions/checkout@v2
        
    # setup nuget
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
        
    # copy zip to staging
    - name: Build solution
      run: |
        mkdir staging
        copy .\Deploy\Tailwind.Traders.web.zip .\staging
        copy .\Deploy\AzCLI\deployWebApp.ps1 .\staging

    - name: show staging
      run: |
        echo cd staging
        cd staging
        echo pwd
        pwd
        echo ls
        ls

    # upload build artifact
    - name: Publish build artifacts back to GitHub
      uses: actions/upload-artifact@master
      with:
        name: webapp
        path: staging

  deployToStaging:
    needs: [build]
    if: (github.event_name == 'pull_request' && github.event.action != 'closed') 
    runs-on: ubuntu-latest
    steps:
      
      # download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@master
        with:
          name: webapp

      # display web app directory for debugging
      - name: show webapp directory
        run: |
          echo ls
          ls

      # deploy web app
      - name: Deploy web app to correct slot
        env:
          SERVICE_PRINCIPAL: http://pdt0507att
          SERVICE_PRINCIPAL_TENANT: 72f988bf-86f1-41af-91ab-2d7cd011db47
          RESOURCE_GROUP: TailwindTradersRG
          WEB_APP_NAME: tailwindtradersgk54hdf3a7sng
          PATH_TO_WEBSITE_ZIP: ./Tailwind.Traders.web.zip
          PR_NUMBER: 12
        run: |
          az login --service-principal --username ${SERVICE_PRINCIPAL} --password ${{ secrets.SERVICE_PRINCIPAL_SECRET }} --tenant ${SERVICE_PRINCIPAL_TENANT}
          az webapp deployment slot create --name ${WEB_APP_NAME} --resource-group ${RESOURCE_GROUP} --slot TailwindsTraders-pr-${PR_NUMBER}
          az webapp deployment source config-zip -g ${RESOURCE_GROUP} -n ${WEB_APP_NAME} --src ${PATH_TO_WEBSITE_ZIP} --slot TailwindsTraders-pr-${PR_NUMBER}

      # comment url of staging environment back to PR
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@1.0.0
        with:
          # Message that should be printed in the pull request
          message: Created staging environment - https://abeltailwindstraders-tailwindstraders-pr-19.azurewebsites.net/
          # Github token of the repository (automatically created by Github)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  closePullRequestJob:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed')
    runs-on: windows-latest
    steps:
      
      # delete staging slot
      - name: Delete staging slot
        env:
          SERVICE_PRINCIPAL: http://pdt0507att
          SERVICE_PRINCIPAL_TENANT: 72f988bf-86f1-41af-91ab-2d7cd011db47
          RESOURCE_GROUP: TailwindTradersRG
          WEB_APP_NAME: tailwindtradersgk54hdf3a7sng
        run: |
          az login --service-principal --username %SERVICE_PRINCIPAL% --password ${{ secrets.SERVICE_PRINCIPAL_SECRET }} --tenant %SERVICE_PRINCIPAL_TENANT%
          az webapp deployment slot create --name %WEB_APP_NAME% --resource-group %RESOURCE_GROUP% --slot TailwindsTraders-pr-${PR_NUMBER}
          az webapp deployment slot delete --name %WEB_APP_NAME% --resource-group %RESOURCE_GROUP% --slot TailwindsTraders-pr-${PR_NUMBER}
